[package]
name = "AptosVotingCore"
version = "1.0.0"
upgrade_policy = "compatible"
authors = ["ni99chain contributors"]

[addresses]
aptos_voting = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "eea778c2276e302119d6e469ec3dd0b78fcce039"
subdir = "aptos-framework"

[dev-dependencies]
